/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-talYaliStav
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_TALYALISTAV_API_H
#define INCLUDED_TALYALISTAV_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_talYaliStav_EXPORTS
#define TALYALISTAV_API __GR_ATTR_EXPORT
#else
#define TALYALISTAV_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_TALYALISTAV_API_H */
